VERSION = '1.0'

from .problema_solucion_inocente import problema_solucion_inocente
from .problema_solucion_meomizado import problema_solucion_meomizado
from .problema_solucion_bottom_up import problema_solucion_bottom_up
from .problema_solucion_bottom_up import obtener_numeros_seleccionados